spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: root
    #password: ENC(+UVRlay47cQ8h4HDBhhlwrHcLi0xklHs4CFMRxJwtJE=)
    password: root

server:
  port: 9090

jasypt:
  encryptor:
    password: ${APP_KEYSTORE_ENCRYPTOR_PASSWORD:localDev}
    algorithm: ${APP_KEYSTORE_ENCRYPTOR_ALGORITHM:PBEWITHSHAAND256BITAES-CBC-BC}
    provider-name: ${APP_KEYSTORE_ENCRYPTOR_PROVIDER:BC}
    bean: jasyptStringEncryptor


app:
  security:
    dataEncryptionEnabled: true


encrypted:
  property: ENC(+UVRlay47cQ8h4HDBhhlwrHcLi0xklHs4CFMRxJwtJE=)


