spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: root
    password: ENC(S6ubHPds3CJKk7vAG4knp8sPF0QSTd65FVVgl4v/3Uo=)

server:
  port: 9090

jasypt:
  encryptor:
    password: localPassword
